import { Inter } from "next/font/google";
import Navbar from "@/components/navbar/navbar";
import type { Metadata } from "next";
import type { ReactNode } from "react";
import ReactQueryProvider from "@/providers/react-query";
import { Toaster } from "sonner";
import "./globals.css";
import { NextUIProvider } from "@/components/nextui";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options";

/*

                                                     __----~~~~~~~~~~~------___
                                    .  .   ~~//====......          __--~ ~~
                    -.            \_|//     |||\\  ~~~~~~::::... /~
                 ___-==_       _-~o~  \/    |||  \\            _/~~-
         __---~~~.==~||\=_    -_--~/_-~|-   |\\   \\        _/~
     _-~~     .=~    |  \\-_    '-~7  /-   /  ||    \      /
   .~       .~       |   \\ -_    /  /-   /   ||      \   /
  /  ____  /         |     \\ ~-_/  /|- _/   .||       \ /
  |~~    ~~|--~~~~--_ \     ~==-/   | \~--===~~        .\
           '         ~-|      /|    |-~\~~       __--~~
                       |-~~-_/ |    |   ~\_   _-~            /\
                            /  \     \__   \/~                \__
                        _--~ _/ | .-~~____--~-/                  ~~==.
                       ((->/~   '.|||' -_|    ~~-/ ,              . _||
                                  -_     ~\      ~~---l__i__i__i--~~_/
                                  _-~-__   ~)  \--______________--~~
                                //.-~~~-~_--~- |-------~~~~~~~~
                                       //.-~~~--\
                    神獸保佑                能進 Dcard
                    神獸保佑                程式碼沒Bug!

*/

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "NextAuth Demo",
};

type RootLayoutProps = {
  children: ReactNode;
};

const RootLayout = async ({ children }: RootLayoutProps) => {
  const session = await getServerSession(options);

  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <NextUIProvider>
            <Toaster position="top-right" richColors />
            <Navbar session={session} />
            <div className="min-w-screen min-h-screen">{children}</div>
          </NextUIProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
